//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiApi.Enteties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public int Employee_Id { get; set; }
        public string Vehicle_Id { get; set; }
        public int PrimaryFuel_ID { get; set; }
        public Nullable<int> SecondaryFuel_ID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public Nullable<decimal> PrimaryFuelAmount { get; set; }
        public Nullable<decimal> PrimaryFuelUnitPrice { get; set; }
        public Nullable<decimal> SecondaryFuelAmount { get; set; }
        public Nullable<decimal> SecondaryFuelUnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> Distance { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual VehicleFuel VehicleFuel { get; set; }
        public virtual VehicleFuel VehicleFuel1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
