//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiApi.Enteties
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleFuel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleFuel()
        {
            this.Report = new HashSet<Report>();
            this.Report1 = new HashSet<Report>();
        }
    
        public int Id { get; set; }
        public int Fuel_Id { get; set; }
        public string Vehicle_Id { get; set; }
    
        public virtual Fuel Fuel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
